### Get contents of folder
GET http://localhost:5000/SASjsApi/drive/folder?_path=/Public/app/react-seed-app/services/web

###
POST http://localhost:5000/SASjsApi/drive/deploy
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJjbGllbnRJRDEiLCJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlzYWRtaW4iOmZhbHNlLCJpc2FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjM1ODA0MDc2LCJleHAiOjE2MzU4OTA0NzZ9.Cx1F54ILgAUtnkit0Wg1K1YVO2RdNjOnTKdPhUtDm5I

### multipart upload to sas server file
POST http://localhost:5000/SASjsApi/drive/file
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="filePath"

/saad/files/new.sas
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="sample_new.sas"
Content-Type: application/octet-stream

< ./sample.sas
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### multipart upload to sas server file text
POST http://localhost:5000/SASjsApi/drive/file
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
  
------WebKitFormBoundary7MA4YWxkTrZu0gW \n
Content-Disposition: form-data; name="filePath"

/saad/files/new2.sas
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="sample_new.sas"
Content-Type: text/plain

SOME CONTENTS OF SAS FILE IN REQUEST

------WebKitFormBoundary7MA4YWxkTrZu0gW--


Users
  "username": "username1",
  "password": "some password",

  "username": "username2",
  "password": "some password",
Admins
  "username": "secretuser",
  "password": "secretpassword",