import { RequestHandler } from 'express'
import { Request } from 'express'
import csrf from 'csrf'

declare module 'express-session' {
  interface SessionData {
    csrfSecret?: string
  }
}

const csrfTokens = new csrf()

/**
 * CSRF tokens must be bound to the session they were minted for.
 *
 * The previous implementation minted ONE process-level secret at startup and
 * derived every token from it, so any token verified for any user/session -
 * a token harvested from an anonymous visit (the public GET / injects one
 * into the page) authenticated state-changing requests for any logged-in
 * browser. The `csrf` library supports per-session secrets directly
 * (`create(secret)` / `verify(secret, token)`); we keep a secret per express
 * session in `req.session` so a token from session A can never satisfy
 * session B.
 *
 * Desktop mode has no session store at all - `configureExpressSession` only
 * mounts the session middleware in server mode. A per-user in-memory secret
 * map keyed by the session id keeps desktop working while still isolating
 * sessions from each other.
 */
const desktopSecrets = new Map<string, string>()

const getSecret = (req: Request): string => {
  if (req.session) {
    if (!req.session.csrfSecret) {
      req.session.csrfSecret = csrfTokens.secretSync()
    }
    return req.session.csrfSecret
  }

  // Desktop mode (or any session-less request): one secret per session id,
  // generated on first use. Session ids are unique per visitor.
  const key = req.sessionID || 'anonymous'
  let secret = desktopSecrets.get(key)
  if (!secret) {
    secret = csrfTokens.secretSync()
    desktopSecrets.set(key, secret)
  }
  return secret
}

export const generateCSRFToken = (req: Request) =>
  csrfTokens.create(getSecret(req))

export const csrfProtection: RequestHandler = (req, res, next) => {
  if (req.method === 'GET') return next()

  // Reads the token from the following locations, in order:
  // req.body.csrf_token - typically generated by the body-parser module.
  // req.headers['csrf-token'] - the CSRF-Token HTTP request header.
  // req.headers['xsrf-token'] - the XSRF-Token HTTP request header.
  // req.headers['x-csrf-token'] - the X-CSRF-Token HTTP request header.
  // req.headers['x-xsrf-token'] - the X-XSRF-Token HTTP request header.
  //
  // The query string is deliberately NO LONGER accepted: a query-string token
  // is attacker-controllable in cross-site form/img/link requests (the
  // browser appends the full URL including ?csrf_token=... with no
  // preflight), which defeats the point of the check.

  const token =
    req.body?.csrf_token ||
    req.headers['csrf-token'] ||
    req.headers['xsrf-token'] ||
    req.headers['x-csrf-token'] ||
    req.headers['x-xsrf-token']

  if (!csrfTokens.verify(getSecret(req), token)) {
    return res.status(400).send('Invalid CSRF token!')
  }
  next()
}
