/**
 * Escaping for the text this server writes into generated stored-program
 * source.
 *
 * A stored program is generated by string concatenation: the caller's query
 * parameters and the signed-in user's display name are written straight into
 * the generated file. Anything that reaches that text unescaped can close the
 * literal it was meant to be part of and run as code in the spawned
 * interpreter, which is a privilege boundary the permission model advertises as
 * real - `/SASjsApi/stp/execute` is grantable to a user who should be able to
 * run one stored program, not arbitrary code.
 *
 * So every value goes through `asLiteral` and every parameter name through
 * `isValidSasName`.
 */

/**
 * A v7 SAS name - what a stored-program parameter may be called.
 *
 * The same names are emitted as identifiers in JavaScript, Python and R and as
 * macro variable names in SAS, so the rule is the strictest of the four: a
 * letter or underscore first, then letters, digits and underscores. It also
 * keeps parameters usable from a SAS program, which is where most stored
 * programs read them.
 */
export const SAS_NAME_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/

export const isValidSasName = (name: string): boolean =>
  SAS_NAME_PATTERN.test(name)

/**
 * The caller's parameters that can be emitted safely, and the ones that cannot.
 * Callers reach this with validated input, so a dropped name means the request
 * path let something through - it is reported rather than emitted.
 */
export const partitionParameterNames = (vars: {
  [key: string]: unknown
}): { safe: string[]; dropped: string[] } => {
  const safe: string[] = []
  const dropped: string[] = []

  Object.keys(vars).forEach((name) => {
    if (isValidSasName(name)) safe.push(name)
    else dropped.push(name)
  })

  return { safe, dropped }
}

/**
 * Names that cannot be emitted are reported rather than silently ignored: a
 * program that expects one of them would otherwise fail with an undefined
 * variable and no clue why.
 */
export const reportDroppedParameterNames = (dropped: string[]): void => {
  if (dropped.length)
    process.logger?.warn(
      `Ignoring stored-program parameters that are not valid SAS names (letters, digits and underscores, starting with a letter or underscore): ${dropped.join(', ')}`
    )
}

/**
 * A value as a double-quoted string literal.
 *
 * JSON's string syntax is also valid JavaScript, Python and R, so one encoding
 * serves all three generators. It cannot be broken out of: quotes, backslashes,
 * control characters and line terminators are escaped, and the result is always
 * exactly one well-formed literal - which is the property the previous
 * template-literal and single-quoted interpolations did not have.
 */
export const asLiteral = (value: unknown): string =>
  JSON.stringify(value === undefined || value === null ? '' : String(value))

/**
 * A value as SAS macro-quoted text, for a `%let` statement.
 *
 * This mirrors what the Viya compute server does to every incoming job
 * variable value (SAS Viya Platform: Programming Run-Time Servers, "Input
 * Parameters"): the semicolon is replaced with a blank character, and the
 * single quote, double quote, ampersand and percent sign are masked with a
 * macro quoting function - here %nrstr, which also stops & triggering macro
 * resolution. %nrstr cannot contain a bare unmatched quote or parenthesis, so
 * each of those is %-marked per the %STR rules.
 */
export const asSasMacroValue = (value: unknown): string => {
  const text = value === undefined || value === null ? '' : String(value)

  return `%nrstr(${text
    .replace(/;/g, ' ')
    .replace(/%/g, '%%')
    .replace(/(['"()])/g, '%$1')})`
}

/**
 * A display name as it is safe to store.
 *
 * Display names come from the identity provider's `name` claim or from an
 * admin, and end up in generated source, in a webout header and in the UI.
 * Escaping is what makes them inert in the generated program (see `asLiteral`);
 * this is the backstop, and it is deliberately narrow: control characters go,
 * the length is bounded, and everything else - accents, apostrophes, non-Latin
 * scripts - is left alone, because mangling a person's name is a worse bug than
 * the one it would be defending against.
 */
export const MAX_DISPLAY_NAME_LENGTH = 64

export const sanitiseDisplayName = (value: unknown): string =>
  String(value ?? '')
    // eslint-disable-next-line no-control-regex
    .replace(/[\u0000-\u001F\u007F]/g, '')
    .trim()
    .slice(0, MAX_DISPLAY_NAME_LENGTH)
