name: SASjs Server Build

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - run: npx prettier -v

      - name: Check Api Code Style
        run: npm run lint-api

      - run: npx prettier -v

      - name: Check Web Code Style
        run: npm run lint-web

  build-api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        working-directory: ./api
        run: npm ci

      - name: Run Unit Tests
        working-directory: ./api
        run: npm test
        env:
          CI: true
          MODE: 'server'
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
          REFRESH_TOKEN_SECRET: ${{secrets.REFRESH_TOKEN_SECRET}}
          AUTH_CODE_SECRET: ${{secrets.AUTH_CODE_SECRET}}
          SESSION_SECRET: ${{secrets.SESSION_SECRET}}

      - name: Build Package
        working-directory: ./api
        run: npm run build
        env:
          CI: true

  build-web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        working-directory: ./web
        run: npm ci

      # TODO: Uncomment next step when unit tests provided
      # - name: Run Unit Tests
      #   working-directory: ./web
      #   run: npm test

      - name: Build Package
        working-directory: ./web
        run: npm run build
        env:
          CI: true
